[project]
name = "ipfs-tools"
version = "0.1.0"
description = "Tools for working with IPFS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.14",
    "fsspec>=2025.3.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
